### ISSUE TITLE
How do you use this? 

### ISSUE THREAD

**Issue by samdup** [schneik80/BOM-Export#4]
Hey there,
Thanks for making this.
I installed this as an addon in Fusion 360 but nothing happens when I run it.
I'm new to add-ins so it wasn't clear how to debug. Any suggestions?

Sam

**Comment by schneik80** [comment]
Are you on Mac or Windows?

**Comment by samdup** [comment]
On Mac

**Comment by schneik80** [comment]
I updated the readme with changelist ea4c7da435a1056050dfc0a8f5a1e2643facf30a
